import 'package:get/get.dart';

class LocaleStrings extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'why_limit_happy_to_an_hour': 'Why limit happy to an hour?',
      'login': 'Login',
      'email_id': 'Email ID',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'new_to_trago': 'New to Trago?',
      'register': 'Register',
      'signup': 'Signup',
      'full_name': 'Full Name',
      'full_name_is_required': 'Full Name is required',
      'phone-number_(optional)': 'Phone number (Optional)',
      'phone-number_is_required': 'Phone number is required',
      'date_of_birth': 'Date of birth',
      'continue': 'Continue',
      'joined_us_before': 'Joined us before?',
      'don\'t_worry_it_happenes_please_enter_the_address_associated_with_your_account': 'Don\'t Worry it happens.Please enter the address associated with your account',
      'submit': 'Submit',
      'english': 'English',
      'language': 'Language',
      'email_is_required': 'Email i s Required',
      'password_is_required': 'Password is Required',
      'password_should_be_at_least_6_characters': 'Password should be at least 6 characters',
      'enter_correct_email':'Enter correct email',
      'upload':'Upload',
      'our_products':'Our Products',
      'all_products':'All Products',
      'cigarette':'Cigarette',
      'beer':'Beer',
      'liquor':'Liquor',
      'search_products':'Search Products',
      'home':'Home',
      'contact_Us':'Contact Us',
      'settings':'Settings',
      'suggestions':'Suggestions',
      'Logout':'logout',
      'are_you_sure_you_want_to_logout?':'Are you sure you want to logout?',
      'cancel': 'Cancel',
      "subtotal":'SubTotal: ',
      'delivery_fee':'DELIVERY FEE',
      'total':'TOTAL',
      'not_found':'NOT FOUND',
      'shipping_flat_rate_You_can_swipe_to':'Shipping Flat Rate: \$20. You can swipe to delete cart itmes',
      'shopping':'Shopping',
      'cart':'Cart',
      'i_agree_that_my_age_is_above_21_to':'I agree that my age is above 21 to access Liquor content as per Govt guidelines',
      'get_started':'GET STARTED',
      'shipping_address':'SHIPPING ADDRESS',
      'first_name':'First Name',
      'please_enter_your_first_name':'Please enter your first name',
      'please_enter_your_name':'Please enter your name',
      'please_enter_your_last_name':'Please enter your last name',
      'last_name':'last name',
      'Please_valid_phone_number':'Please enter valid phone number ',
      'phone':'Phone',
      'please_enter_the_address ':'Please enter the address ',
      'enter_your_address':'Enter your address',
      'please_enter_the_state':'Please enter the state ',
      'enter_state':'Enter state',
      'please_enter_the_city_name':'Please enter the city name ',
      'city':'City',
      'please_enter_the_zip_code':'Please enter the zip code ',
      'enter_the_zip_code':'Enter Zip Code (0000)',
      'order_now':'ORDER NOW',
      'please_fill_the_form':'Please fill the form ',
      'send_Email':'Send Email',
      'get_In_Touch':'Get In Touch',
      'Contact_us_for_any_query':"Contact us for any query. You can email or what's app by click ",
      'your_name':'Your name',
      'please_enter_the_Subject':'Please enter the Subject',
      'write_message':'Write message ',
      'type_message':'Type Message',
      'send_email':'Send Email',
      'select_language':'Select Language',
      'your_order_is_confirmed':'Your Order is Confirmed!',
      'back_to_home_page ':' BACK TO HOME PAGE ',
      'show_order_summary':" 🛒 Show order summary",
      'select_Payment_Method':'Select Payment Method',
      'cash_on_delivery':'Cash on Delivery',
      'online_payment':'Online payment',
      'place_order':'PLACE ORDER',
      'contact':'Contact',
      'ship_to':'Ship To',
      'click_to_change_delivery_information':'Click to change delivery information',
      "payment_successful":"Payment Successful",
      'enter_phone_number':'Enter phone number',
      'please_enter_your_phone':'Please enter your phone',
      'enter_message_for_rider':'Enter message for rider',
      'change_may_not_be_available_please_have_the_exact_amount':'NOTE: Change may not be available please have the exact amount.',
      'confirm_order':'CONFIRM ORDER',
      'product_Added_to_the_cart':'Product Added to the cart',
      'available_pack':'Available Pack',
      'product_description':'Product Description',
      'add_to_cart':'ADD TO CART',
      'search_results_for':'SEARCH RESULTS FOR:',
      'edit_profile':'Edit Profile',
      'change_password':'Change Password',
      'alert':'Alert',
      "Cant_find_what_you_are_looking_for":"Can't Find What You are Looking for",
      'please_fill_out_this_suggestion_form':'please fill out this suggestion form',
      'please_enter_the_email_address':'Please enter the email address',
      'your_email_address':'Your  email address',
      'suggestion_message':'Suggestion message ',
      'please_write_some_suggestion':'Please write some suggestion',
      'submit_form':'SUBMIT FORM',
      'back_to_home_page':'Back to Home Page',



      },

    'spa_span': {
      'login': 'Acceso',
      'email_id': 'Correo electrónico identificación',
      'password': 'Clave',
      'forgot_password': 'Has olvidado tu contraseña?',
      'new_to_trago': 'Nueva en Trago?',
      'register': 'Registro',
      'signup': 'Inscribirse',
      'full_name': 'Nombre completo',
      'full_name_is_required': 'Se requiere el nombre completo',
      'phone-number_(optional)': 'Número de teléfono(Opcional)',
      'phone-number_is_required': 'Se requiere el número de teléfono',
      'date_of_birth': 'Fecha de nacimiento',
      'continue': 'continuar',
      'joined_us_before': 'Se unió a nosotras antes?',
      'don\'t_worry_it_happenes_please_enter_the_address_associated_with_your_account': 'No te preocupes, sucede. Ingrese la dirección asociada con su cuenta.',
      'submit': 'enviar',
      'english': 'Inglesa',
      'spanish': 'Española',
      'language': 'Idioma',
      'email_is_required': 'Correo electronico es requerido',
      'password_is_required': 'Se requiere contraseña',
      'password_should_be_at_least_6_characters': 'La contraseña debe tener al menos 6 caracteres',
      'enter_correct_email':'Ingrese el correo electrónico correcto',
      'upload':'Subir',
      'our_products':'Nuestros Productos',
      'all_products':'Todos los Productos',
      'cigarette':'Cigarrillo',
      'beer':'Cerveza',
      'liquor':'Espíritu',
      'search_products':'Buscar Productos',
      'home':'Hogar',
      'contact_Us':'Contacta con nosotros',
      'settings':'Ajustes',
      'suggestions':'Sugerencias',
      'are_you_sure_you_want_to_logout?':'Estás seguro de que quieres cerrar sesión?',
      'cancel':'Cancelar',
      'logout':'cerrar sesión',
      'subtotal':'Total parcial: ',
      'delivery_fee':'GASTOS DE ENVÍO',
      'total':'TOTAL',
      'not_found':'Extraviado',
      'shipping_flat_rate_You_can_swipe_to':'Tarifa plana de envío: \$20. Puede deslizar para eliminar elementos del carrito',
      'shopping':'compras',
      'cart':'carro',
      'i_agree_that_my_age_is_above_21_to':'Acepto que mi edad es mayor de 21 años para acceder al contenido de Liquor según las pautas gubernamentales',
      'get_started':'EMPEZAR',
      'shipping_address':'DIRECCIÓN DE ENVÍO',
      'first_name':'Nombre de pila',
      'please_enter_your_first_name':'Por favor, introduzca su nombre de pila',
      'please_enter_your_last_name':'Por favor ingrese su apellido',
      'last_name':'apellido',
      'Please_valid_phone_number':'Por favor, introduzca un número de teléfono válido',
      'phone':'teléfono',
      'please_enter_the_address ':'Por favor ingrese la dirección',
      'enter_your_address':'Introduce tu dirección',
      'please_enter_the_state':'Por favor ingrese el estado ',
      'enter_state':'Ingresar estado',
      'please_enter_the_city_name':'por favor ingrese el nombre de la ciudad',
      'city':'Ciudad',
      'please_enter_the_zip_code':'Por favor ingrese el código postal',
      'enter_the_zip_code':'Ingrese el código postal (0000)',
      'order_now':'ORDENAR AHORA',
      'please_fill_the_form':'Porfavor llene la forma',
      'send_Email':'Enviar correo electrónico',
      'get_In_Touch':'Ponerse en contacto',
      'Contact_us_for_any_query':"Contacte con nosotros para cualquier consulta. Puede enviar un correo electrónico o cuál es la aplicación haciendo clic ",
      'your_name':'Su nombre',
      'please_enter_your_name':'por favor, escriba su nombre',
      'please_enter_the_Subject':'Por favor ingrese el Asunto',
      'subject':'Sujeta',
      'write_message':'Escribe un mensaje ',
      'type_message':'Escriba el mensaje',
      'send_email':'enviar correo electrónico',
      'select_language':'seleccione el idioma',
      'your_order_is_confirmed':'Su pedido está confirmado!',
      'back_to_home_page':'VOLVER A LA PÁGINA DE INICIO',
      'show_order_summary':" 🛒 Mostrar resumen del pedido",
      'select_Payment_Method':'Seleccionar método de pago',
      'cash_on_delivery':'Contrareembolso',
      'online_payment':'Pago en línea',
      'place_order':'REALIZAR PEDIDO',
      'contact':'Contacto',
      'ship_to':'Envie a..',
      'click_to_change_delivery_information':'Haga clic para cambiar la información de entrega',
      "payment_successful":"Pago exitoso",
      'enter_phone_number':'Ingresa número telefónico',
      'please_enter_your_phone':'Por favor ingrese su teléfono',
      'enter_message_for_rider':'Ingrese el mensaje para el jinete',
      'change_may_not_be_available_please_have_the_exact_amount':'NOTA: Es posible que el cambio no esté disponible, tenga a mano la cantidad exacta.',
      'confirm_order':'CONFIRMAR PEDIDO',
      'product_Added_to_the_cart':'Producto Añadido al carrito',
      'available_pack':'Paquete Disponible',
      'product_description':'Descripción del Producto',
      'add_to_cart':'AÑADIR A LA CESTA',
      'search_results_for':'RESULTADOS DE BÚSQUEDA PARA:',
      'change_password':'Cambiar la contraseña',
      'alert':'Alerta',
      "Cant_find_what_you_are_looking_for":"No puede encontrar lo que está buscando",
      'please_fill_out_this_suggestion_form':'por favor complete este formulario de sugerencias',
      'please_enter_the_email_address':'Por favor, introduzca la dirección de correo electrónico',
      'your_email_address':'Su dirección de correo electrónico',
      'suggestion_message':'mensaje de sugerencia',
      'please_write_some_suggestion':'Por favor escribe alguna sugerencia',
      'submit_form':'ENVIAR FORMULARIO',
      'edit_profile':'Editar perfil',




    }
  };
}

